### ISSUE TITLE
Cannot deploy multiple cronjobs

### ISSUE THREAD

**Issue by wewelll** [Qovery/qovery-cli#225]
**What happened**:
I'm trying to deploy multiple cronjobs at the same time with the following command: 
```
qovery cronjob deploy --organization "my-org" --project "my-project" --environment "staging" --cronjobs "cron-job-1,cron-job-2" --tag=sha-b71d187 --watch
```

I see the following error: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x98 pc=0x100e951d0]

goroutine 1 [running]:
github.com/qovery/qovery-cli/utils.GetJobDocker(...)
	/home/runner/work/qovery-cli/qovery-cli/utils/qovery.go:1470
github.com/qovery/qovery-cli/utils.DeployJobs(0x140000ba000, {0x140000b22a0, 0x24}, {0x16f40b76c, 0x32}, {0x0, 0x0}, {0x16f40b7a5, 0xb})
	/home/runner/work/qovery-cli/qovery-cli/utils/qovery.go:1427 +0x2b0
github.com/qovery/qovery-cli/cmd.glob..func73(0x1400022d700?, {0x10107692b?, 0x4?, 0x10107692f?})
	/home/runner/work/qovery-cli/qovery-cli/cmd/cronjob_deploy.go:68 +0x598
github.com/spf13/cobra.(*Command).execute(0x1018d3340, {0x14000257220, 0xa, 0xa})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920 +0x654
github.com/spf13/cobra.(*Command).ExecuteC(0x1018c8f60)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x320
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/qovery/qovery-cli/cmd.Execute()
	/home/runner/work/qovery-cli/qovery-cli/cmd/root.go:19 +0x24
main.main()
	/home/runner/work/qovery-cli/qovery-cli/main.go:6 +0x1c

```

This is happening both on my local machine (mac M3) and on github actions

**What you expected to happen**:

I expect it not to throw an error and to deploy my cron-jobs

**How to reproduce it (as minimally and precisely as possible)**:

Try to deploy multiple cron jobs

**Anything else we need to know?**:

Deploying cron jobs 1 by 1 works, for instance:
```
qovery cronjob deploy --organization "my-org" --project "my-project" --environment "staging" --cronjob "cron-job-1" --tag=sha-b71d187 --watch
```

**Environment**:
- Qovery version (use `qovery version`): 0.75.3
- OS and version: maxOS Sonoma 14.1.2 (23B2091)

**Comment by acarranoqovery** [comment]
Hi @wewelll ,

I just tested on two cronjobs on my test account and all works fine.

Can you confirm if you still have the issue?

**Comment by wewelll** [comment]
Hello @acarranoqovery, I don't have this issue anymore 👍
